-- DROP TRIGGER `checkBorrow`; 
delimiter //
CREATE TRIGGER `checkBorrow`
BEFORE INSERT
ON `LOAN`
FOR EACH ROW
BEGIN
	IF((SELECT COUNT(*) FROM LOAN WHERE LOAN.PersonID = NEW.PersonID AND LOAN.LoanID IN (SELECT LoanID FROM LOAN WHERE LOAN.CopyID IN (SELECT CopyID FROM BRANCH_COPIES WHERE BRANCH_COPIES.Category = (SELECT Category FROM BRANCH_COPIES WHERE CopyID = NEW.CopyID)))) = (SELECT Max_Loaned FROM LOAN_TYPE WHERE LOAN_TYPE.TypeOf = (SELECT Type_of_person FROM UNIVERSITY_PERSON WHERE ID = NEW.PersonID AND LOAN_TYPE.Category = (SELECT Category FROM BRANCH_COPIES WHERE BRANCH_COPIES.CopyID = NEW.CopyID))))
		THEN 
			SIGNAL SQLSTATE '45000' 
			SET MESSAGE_TEXT = 'Max number of books reached';
    END IF;
END; //
delimiter ;
