-- DROP TRIGGER `checkRenew`; 
delimiter //
CREATE TRIGGER `checkRenew`
BEFORE UPDATE
ON `LOAN`
FOR EACH ROW
BEGIN
	IF((SELECT Category FROM BRANCH_COPIES WHERE BRANCH_COPIES.CopyID = NEW.CopyID) = 'NEW')
		THEN 
			SIGNAL SQLSTATE '45000' 
			SET MESSAGE_TEXT = 'CANNOT RENEW NEW BOOK';
    ELSEIF(OLD.Extension = 1)
		THEN
			SIGNAL SQLSTATE '45000' 
			SET MESSAGE_TEXT = 'ALREADY RENEWED ONCE';
    ELSEIF (NEW.LoanID IN (SELECT LoanID FROM pastdue WHERE LoanID = NEW.LoanID))
		THEN
			SIGNAL SQLSTATE '45000' 
			SET MESSAGE_TEXT = 'HAS PAST DUE';
    END IF;
END; //
delimiter ;
