DROP DATABASE cs4222_final_project;
CREATE DATABASE cs4222_final_project;
USE cs4222_final_project;

CREATE TABLE BRANCH(
BranchName VARCHAR(15) NOT NULL,
BranchID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (BranchID)
);

CREATE TABLE UNIVERSITY_PERSON(
Type_of_person VARCHAR(15),
Fname VARCHAR(15),
Lname VARCHAR(15),
ID  INT NOT NULL AUTO_INCREMENT,
Gender VARCHAR(6),
Department VARCHAR(256),
Email VARCHAR(256),
Birthdate date,
PRIMARY KEY (ID)
);

CREATE TABLE PUBLISHER(
PublisherID INT NOT NULL AUTO_INCREMENT,
Publisher_name VARCHAR(256),
PRIMARY KEY (PublisherID)
);

CREATE TABLE BOOK(
Type_of_book VARCHAR(15),
Book_name VARCHAR(256),
BookID INT NOT NULL AUTO_INCREMENT,
ISBN VARCHAR(17),
PublisherID INT,
Publish_date DATE,
Number_of_words INT,
Price VARCHAR(15),
Brief_introduction VARCHAR(256),
PRIMARY KEY (BookID),
FOREIGN KEY (PublisherID) REFERENCES PUBLISHER(PublisherID)
);

CREATE TABLE AUTHOR(
AuthorID INT NOT NULL AUTO_INCREMENT,
Fname VARCHAR(15),
Lname VARCHAR(15),
PRIMARY KEY (AuthorID)
);

CREATE TABLE BOOK_AUTHOR(
BookID INT,
AuthorID INT,
FOREIGN KEY (AuthorID) REFERENCES AUTHOR(AuthorID),
FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);

CREATE TABLE BRANCH_COPIES(
BranchID INT,
BookID INT,
CopyID INT NOT NULL AUTO_INCREMENT,
Add_date DATE,
Available VARCHAR(255),
Category VARCHAR(255),
PRIMARY KEY (CopyID),
FOREIGN KEY (BranchID) REFERENCES BRANCH(BranchID),
FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);

CREATE TABLE LOAN(
LoanID INT NOT NULL AUTO_INCREMENT,
Loan_date DATE,
Due_date DATE,
Extension BOOL,
PersonID INT,
CopyID INT,
BranchID INT,
PRIMARY KEY (LoanID),
FOREIGN KEY (CopyID) REFERENCES BRANCH_COPIES(CopyID),
FOREIGN KEY (PersonID) REFERENCES UNIVERSITY_PERSON(ID),
FOREIGN KEY (BranchID) REFERENCES BRANCH_COPIES(BranchID)
);


CREATE TABLE BORROWER(
Borrower_username VARCHAR(15),
Borrower_password VARCHAR(15),
PersonID INT,
FOREIGN KEY (PersonID) REFERENCES UNIVERSITY_PERSON(ID)
);

CREATE TABLE PASTDUE(
LoanID INT,
Amountdue VARCHAR(15),
FOREIGN KEY (LoanID) REFERENCES LOAN(LoanID)
);

CREATE TABLE RETURNSTRACKER(
Return_date DATE,
LoanID INT,
ReturnID INT NOT NULL AUTO_INCREMENT,
BranchID INT,
PRIMARY KEY (ReturnID),
FOREIGN KEY (LoanID) REFERENCES LOAN(LoanID)
);

CREATE TABLE LOAN_TYPE(
	TypeOf VARCHAR(255),
    Category VARCHAR(255),
    Max_loaned VARCHAR(255),
    Loan_period VARCHAR(255),
    Extension VARCHAR(255),
    LateFine VARCHAR(255)
);


