DROP PROCEDURE INQUIRYBorrow()
delimiter //
CREATE PROCEDURE INQUIRYBorrow(
	IN Borrower INT)
BEGIN
	SELECT * FROM LOAN WHERE LOAN.PersonID = Borrower AND LOAN.LoanID NOT IN (SELECT LoanID FROM RETURNSTRACKER);
    SELECT COUNT(*) FROM LOAN WHERE LOAN.PersonID = Borrower AND LOAN.LoanID NOT IN (SELECT LoanID FROM RETURNSTRACKER);
    IF NOT EXISTS(SELECT * FROM BORROWER WHERE BORROWER.PersonID = Borrower)
		THEN
		INSERT INTO BORROWER(Borrower_username, Borrower_password, PersonID)
        VALUES
			(Borrower, (SELECT Birthday FROM UNIVERSITY_PERSON WHERE UNIVBERSITY_PERSON.ID = Borrower), Borrower);
		END IF;
END; //
delimiter ;