-- DROP PROCEDURE pastDueAdd;
delimiter //
CREATE PROCEDURE pastDueAdd()
BEGIN
	WHILE EXISTS(SELECT * FROM LOAN WHERE CURDATE() > LOAN.Due_date AND LOAN.LoanID NOT IN(SELECT LoanID FROM PASTDUE)) DO
		SET @Loan = (SELECT LoanID FROM LOAN WHERE CURDATE() > LOAN.Due_date AND LOAN.LoanID NOT IN(SELECT LoanID FROM PASTDUE) LIMIT 1);
		INSERT INTO PASTDUE(LoanID, AmountDue) VALUES ((SELECT @Loan), 0);
    END WHILE;
    UPDATE PASTDUE SET Amountdue = (datediff(curdate(), (SELECT Due_date FROM LOAN WHERE LOAN.LoanID = Pastdue.LoanID)) * (SELECT LateFine FROM LOAN_TYPE WHERE LOAN_TYPE.TypeOf = (SELECT Type_of_person FROM UNIVERSITY_PERSON WHERE UNIVERSITY_PERSON.ID = (SELECT PersonID FROM LOAN WHERE LOAN.LoanID = PASTDUE.LoanID)) AND LOAN_TYPE.Category = (SELECT Category FROM BRANCH_COPIES WHERE BRANCH_COPIES.CopyID = (SELECT CopyID FROM LOAN WHERE LOAN.LoanID = PASTDUE.LoanID))));
END; //
delimiter ;